<?php

namespace App\Services\AI\Interfaces;

interface AIServiceInterface
{
    /**
     * Generates text based on a prompt
     *
     * @param string $prompt The input text to generate a response
     * @param array $options Additional options to configure the generation
     * @return string The text generated by the AI
     */
    public function generateText(string $prompt, array $options = []): string;
    
    /**
     * Generates an image based on a prompt
     *
     * @param string $prompt The description to generate the image
     * @param array $options Additional options to configure the generation
     * @return string URL or data of the generated image
     */
    public function generateImage(string $prompt, array $options = []): string;
    
    /**
     * Analyzes the sentiment of a text
     *
     * @param string $text The text to analyze
     * @return array Information about the sentiment of the text
     */
    public function analyzeSentiment(string $text): array;
    
    /**
     * Extracts entities from a text
     *
     * @param string $text The text to analyze
     * @return array The identified entities
     */
    public function extractEntities(string $text): array;
}