<?php

namespace App\Repositories\Interfaces;

interface AIRepositoryInterface
{
    /**
     * Get a text response from the AI
     *
     * @param string $prompt The input text
     * @param array $options Additional options
     * @return string The generated response
     */
    public function getTextResponse(string $prompt, array $options = []): string; 
    
    /**
     * Analyze the sentiment of a text
     *
     * @param string $text The text to analyze
     * @return array Information about the sentiment
     */
    public function getSentimentAnalysis(string $text): array;
    
    /**
     * Get the entities of a text
     *
     * @param string $text The text to analyze
     * @return array The identified entities
     */
    public function getEntities(string $text): array;

    
    
    /**
     * Get an image generated by the AI
     *
     * @param string $prompt The description to generate the image
     * @param array $options Additional options
     * @return string URL or image data
     */
    public function getImageResponse(string $prompt, array $options = []): string;
    
    /**
     * Change the AI provider
     *
     * @param string $provider The new provider to use
     * @return void
     */
    public function setProvider(string $provider): void;
}